pipeline {
    agent {
        node { 
            label 'node'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/alonsoaguirreazorin/prueba-next-digital.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t test-next-digital .'
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    def login = sh(script: 'aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin your-account-id.dkr.ecr.your-region.amazonaws.com', returnStdout: true)
                }

                sh 'docker tag test-next-digital:latest your-account-id.dkr.ecr.your-region.amazonaws.com/test-next-digital:latest'

                sh 'docker push your-account-id.dkr.ecr.your-region.amazonaws.com/test-next-digital:latest'
            }
        }
    }
}
